import { registerSwatches } from "@/lib/swatches";

/** Cores oficiais dos iPhones (amostra visual aproximada). Gerado do catálogo. */
registerSwatches({
  "(PRODUCT)RED": "#E11C2A",
  "Amarelo": "#EEE4B8",
  "Azul": "#D4E1E9",
  "Azul-Pacífico": "#2F4452",
  "Azul-Sierra": "#A7C1D9",
  "Azul-céu": "#BFD5E8",
  "Azul-intenso": "#2E3A57",
  "Azul-névoa": "#A9BCD0",
  "Branco": "#F4F4F1",
  "Branco-nuvem": "#F4F4F2",
  "Dourado": "#F4E8CE",
  "Dourado-claro": "#E9DCC2",
  "Estelar": "#F0EBE3",
  "Grafite": "#54524F",
  "Laranja-cósmico": "#E8742F",
  "Lavanda": "#D7C9E8",
  "Meia-noite": "#222930",
  "Prateado": "#E3E4E1",
  "Preto": "#2A2B2E",
  "Preto-espacial": "#2B2C30",
  "Rosa": "#F2ADDA",
  "Rosa-pálido": "#F1D3D6",
  "Roxo": "#E5DDEA",
  "Roxo-profundo": "#594F63",
  "Sálvia": "#B7C3A6",
  "Titânio azul": "#3F4A58",
  "Titânio branco": "#F2F1ED",
  "Titânio natural": "#C2BCB2",
  "Titânio preto": "#3C3C3D",
  "Titânio-deserto": "#BFA48F",
  "Ultramarino": "#9AADF6",
  "Verde": "#CAD4C5",
  "Verde-acinzentado": "#B0D4D2",
  "Verde-alpino": "#576856",
});
