/**
 * Catálogo DEMO (somente desenvolvimento). Produtos e preços aproximados do
 * mercado brasileiro, marcados como isDemo. Imagens: ilustrações geradas
 * (/demo-assets). Nada aqui deve ir para produção (SEED_MODE=minimal).
 */
export type DemoProduct = {
  slug: string;
  name: string;
  cat: string;
  brand?: string;
  store: "mercatto" | "technova" | "casaviva" | "urbanstep" | "bellapele" | "garagempro";
  kind: string;
  /** Opções de variação. A opção "Cor" usa o mapa colors para imagem. */
  options?: Record<string, string[]>;
  colors?: Record<string, string>;
  /** Cor da arte quando não há opção de cor. */
  color?: string;
  price: number; // centavos (variante base)
  compare?: number;
  /** Acréscimo de preço por valor de opção (centavos). */
  step?: Record<string, number>;
  stock?: "high" | "low" | "zero" | "mixed";
  about: string;
  specs: [string, string][];
  attrs?: Record<string, string>;
  /** Atributo por valor de opção (ex.: armazenamento da variante principal). */
  tags?: string[];
  warranty?: number;
  included?: string[];
  weight: number; // gramas
  dims: [number, number, number]; // A, L, C (cm)
  freeShipping?: boolean;
  featured?: boolean;
  condition?: "NEW" | "USED" | "REFURBISHED";
  status?: "DRAFT" | "PAUSED";
};

const phoneColors = { Preto: "black", Branco: "white", Azul: "blue", Rosa: "pink", Verde: "green", Grafite: "graphite", Dourado: "gold", Roxo: "purple", Prata: "silver" };
const pick = (keys: string[]) => Object.fromEntries(keys.map((k) => [k, phoneColors[k as keyof typeof phoneColors]]));

export const DEMO_PRODUCTS: DemoProduct[] = [
  // ------------------------------------------------------------ Smartphones
  { slug: "apple-iphone-16", name: "Apple iPhone 16", cat: "smartphones", brand: "apple", store: "mercatto", kind: "smartphone", options: { Armazenamento: ["128 GB", "256 GB", "512 GB"], Cor: ["Preto", "Branco", "Rosa", "Verde"] }, colors: pick(["Preto", "Branco", "Rosa", "Verde"]), price: 599900, compare: 699900, step: { "256 GB": 80000, "512 GB": 200000 }, about: "O iPhone 16 traz o chip A18, câmera Fusion de 48 MP e o novo botão de Controle da Câmera para fotos e vídeos ainda mais rápidos.", specs: [["Tela", '6,1" Super Retina XDR OLED'], ["Processador", "A18"], ["Câmera traseira", "48 MP + 12 MP ultra-angular"], ["Câmera frontal", "12 MP"], ["Bateria", "Até 22 h de vídeo"], ["Conectividade", "5G, Wi‑Fi 7, NFC"]], attrs: { armazenamento: "128 GB", memoria_ram: "8 GB", rede_5g: "Sim" }, tags: ["iphone", "ios", "5g"], warranty: 12, included: ["iPhone 16", "Cabo USB-C"], weight: 170, dims: [15, 7, 1], freeShipping: true, featured: true },
  { slug: "apple-iphone-15", name: "Apple iPhone 15", cat: "smartphones", brand: "apple", store: "technova", kind: "smartphone", options: { Armazenamento: ["128 GB", "256 GB"], Cor: ["Preto", "Azul", "Rosa"] }, colors: pick(["Preto", "Azul", "Rosa"]), price: 469900, compare: 529900, step: { "256 GB": 70000 }, about: "Dynamic Island, câmera principal de 48 MP e USB-C. Um iPhone completo para o dia a dia.", specs: [["Tela", '6,1" OLED'], ["Processador", "A16 Bionic"], ["Câmera", "48 MP + 12 MP"], ["Conectividade", "5G, NFC"]], attrs: { armazenamento: "128 GB", memoria_ram: "6 GB", rede_5g: "Sim" }, tags: ["iphone", "ios"], warranty: 12, included: ["iPhone 15", "Cabo USB-C"], weight: 171, dims: [15, 7, 1] },
  { slug: "samsung-galaxy-s24", name: "Samsung Galaxy S24 5G", cat: "smartphones", brand: "samsung", store: "mercatto", kind: "smartphone", options: { Armazenamento: ["128 GB", "256 GB"], Cor: ["Preto", "Roxo", "Prata"] }, colors: pick(["Preto", "Roxo", "Prata"]), price: 399900, compare: 499900, step: { "256 GB": 50000 }, about: "Galaxy AI integrada para tradução em tempo real, edição de fotos inteligente e resumos. Tela Dynamic AMOLED 2X de 120 Hz.", specs: [["Tela", '6,2" Dynamic AMOLED 2X 120 Hz'], ["Processador", "Exynos 2400"], ["Câmera", "50 MP + 12 MP + 10 MP"], ["Bateria", "4.000 mAh"]], attrs: { armazenamento: "128 GB", memoria_ram: "8 GB", rede_5g: "Sim" }, tags: ["galaxy", "android", "5g"], warranty: 12, included: ["Smartphone", "Cabo USB-C", "Ferramenta de chip"], weight: 167, dims: [15, 7, 1], freeShipping: true, featured: true },
  { slug: "samsung-galaxy-a55", name: "Samsung Galaxy A55 5G", cat: "smartphones", brand: "samsung", store: "technova", kind: "smartphone", options: { Armazenamento: ["128 GB", "256 GB"], Cor: ["Azul", "Preto"] }, colors: pick(["Azul", "Preto"]), price: 199900, compare: 249900, step: { "256 GB": 30000 }, about: "Design premium em vidro e metal, resistência à água IP67 e câmera de 50 MP com estabilização óptica.", specs: [["Tela", '6,6" Super AMOLED 120 Hz'], ["Câmera", "50 MP OIS"], ["Bateria", "5.000 mAh"]], attrs: { armazenamento: "128 GB", memoria_ram: "8 GB", rede_5g: "Sim" }, tags: ["galaxy", "android"], warranty: 12, included: ["Smartphone", "Cabo USB-C"], weight: 213, dims: [17, 8, 1] },
  { slug: "motorola-edge-50", name: "Motorola Edge 50 Pro", cat: "smartphones", brand: "motorola", store: "technova", kind: "smartphone", options: { Armazenamento: ["256 GB", "512 GB"], Cor: ["Preto", "Roxo"] }, colors: pick(["Preto", "Roxo"]), price: 249900, compare: 329900, step: { "512 GB": 40000 }, about: "Carregamento TurboPower de 125 W, tela curva pOLED de 144 Hz e câmera validada pela Pantone.", specs: [["Tela", '6,7" pOLED 144 Hz'], ["Carregamento", "125 W"], ["Câmera", "50 MP"]], attrs: { armazenamento: "256 GB", memoria_ram: "12 GB", rede_5g: "Sim" }, tags: ["motorola", "android"], warranty: 12, included: ["Smartphone", "Carregador 125 W", "Capa"], weight: 186, dims: [17, 8, 1] },
  { slug: "motorola-moto-g85", name: "Motorola Moto G85 5G", cat: "smartphones", brand: "motorola", store: "mercatto", kind: "smartphone", options: { Cor: ["Azul", "Grafite"] }, colors: pick(["Azul", "Grafite"]), price: 139900, compare: 179900, about: "Tela pOLED curva de 120 Hz, som Dolby Atmos e câmera de 50 MP com OIS por um preço acessível.", specs: [["Tela", '6,67" pOLED 120 Hz'], ["Armazenamento", "256 GB"], ["RAM", "8 GB"]], attrs: { armazenamento: "256 GB", memoria_ram: "8 GB", rede_5g: "Sim" }, tags: ["moto g"], warranty: 12, included: ["Smartphone", "Carregador", "Capa"], weight: 172, dims: [17, 8, 1], freeShipping: true },
  { slug: "xiaomi-redmi-note-13", name: "Xiaomi Redmi Note 13 Pro", cat: "smartphones", brand: "xiaomi", store: "technova", kind: "smartphone", options: { Armazenamento: ["256 GB", "512 GB"], Cor: ["Preto", "Roxo", "Branco"] }, colors: pick(["Preto", "Roxo", "Branco"]), price: 189900, compare: 239900, step: { "512 GB": 30000 }, about: "Câmera de 200 MP, tela AMOLED 1,5K e carregamento rápido de 67 W.", specs: [["Tela", '6,67" AMOLED 1,5K'], ["Câmera", "200 MP"], ["Carregamento", "67 W"]], attrs: { armazenamento: "256 GB", memoria_ram: "8 GB", rede_5g: "Não" }, tags: ["xiaomi", "redmi"], warranty: 12, weight: 187, dims: [17, 8, 1], stock: "low" },
  { slug: "xiaomi-poco-x6", name: "Xiaomi Poco X6 Pro 5G", cat: "smartphones", brand: "xiaomi", store: "technova", kind: "smartphone", options: { Cor: ["Preto", "Amarelo"] }, colors: { Preto: "black", Amarelo: "yellow" }, price: 199900, about: "Desempenho gamer com Dimensity 8300-Ultra e tela Flow AMOLED de 120 Hz.", specs: [["Processador", "Dimensity 8300-Ultra"], ["RAM", "12 GB"], ["Armazenamento", "512 GB"]], attrs: { armazenamento: "512 GB", memoria_ram: "12 GB", rede_5g: "Sim" }, tags: ["poco", "gamer"], warranty: 12, weight: 186, dims: [17, 8, 1], stock: "zero" },
  { slug: "iphone-13-recondicionado", name: "Apple iPhone 13 128 GB — Recondicionado", cat: "smartphones", brand: "apple", store: "technova", kind: "smartphone", color: "blue", price: 259900, compare: 329900, about: "Aparelho recondicionado e testado em 40 pontos, bateria com saúde acima de 85%.", specs: [["Condição", "Recondicionado — excelente"], ["Saúde da bateria", "≥ 85%"], ["Garantia", "6 meses"]], attrs: { armazenamento: "128 GB", memoria_ram: "4 GB", rede_5g: "Sim" }, tags: ["seminovo"], warranty: 6, weight: 174, dims: [15, 7, 1], condition: "REFURBISHED" },
  // ------------------------------------------------------------ Smartwatches / fones
  { slug: "apple-watch-series-10", name: "Apple Watch Series 10 GPS 42 mm", cat: "smartwatches", brand: "apple", store: "mercatto", kind: "smartwatch", options: { Cor: ["Preto", "Prata", "Rosa"] }, colors: pick(["Preto", "Prata", "Rosa"]), price: 449900, compare: 499900, about: "Tela maior e mais brilhante, detecção de apneia do sono e carregamento mais rápido.", specs: [["Tela", "OLED LTPO3"], ["Resistência", "50 m"], ["Sensores", "ECG, oxigênio no sangue, temperatura"]], tags: ["apple watch"], warranty: 12, weight: 90, dims: [10, 10, 5], freeShipping: true },
  { slug: "samsung-galaxy-watch7", name: "Samsung Galaxy Watch7 44 mm", cat: "smartwatches", brand: "samsung", store: "technova", kind: "smartwatch", options: { Cor: ["Verde", "Prata"] }, colors: pick(["Verde", "Prata"]), price: 199900, compare: 249900, about: "Monitoramento de saúde com IA, GPS de dupla frequência e até 40 horas de bateria.", specs: [["Tela", '1,5" Super AMOLED'], ["Bateria", "Até 40 h"]], tags: ["galaxy watch"], warranty: 12, weight: 80, dims: [10, 10, 5] },
  { slug: "xiaomi-smart-band-9", name: "Xiaomi Smart Band 9", cat: "smartwatches", brand: "xiaomi", store: "mercatto", kind: "smartwatch", options: { Cor: ["Preto", "Rosa", "Azul"] }, colors: pick(["Preto", "Rosa", "Azul"]), price: 29990, compare: 39990, about: "Até 21 dias de bateria, mais de 150 modos de treino e tela AMOLED.", specs: [["Bateria", "Até 21 dias"], ["Resistência", "5 ATM"]], tags: ["pulseira inteligente"], warranty: 12, weight: 50, dims: [8, 8, 4], freeShipping: true },
  { slug: "apple-airpods-pro-2", name: "Apple AirPods Pro (2ª geração) USB-C", cat: "fones-de-ouvido", brand: "apple", store: "mercatto", kind: "earbuds", color: "white", price: 189900, compare: 229900, about: "Cancelamento ativo de ruído até 2x melhor, modo Ambiente adaptativo e áudio espacial personalizado.", specs: [["Cancelamento de ruído", "Ativo"], ["Bateria", "Até 30 h com o estojo"], ["Resistência", "IP54"]], tags: ["airpods", "bluetooth"], warranty: 12, included: ["Fones", "Estojo MagSafe", "Pontas de silicone"], weight: 60, dims: [8, 8, 4], freeShipping: true, featured: true },
  { slug: "jbl-tune-buds", name: "Fone JBL Tune Buds", cat: "fones-de-ouvido", brand: "jbl", store: "technova", kind: "earbuds", options: { Cor: ["Preto", "Branco", "Azul"] }, colors: pick(["Preto", "Branco", "Azul"]), price: 49990, compare: 59990, about: "JBL Pure Bass, cancelamento de ruído e até 48 horas de reprodução.", specs: [["Bateria", "Até 48 h"], ["Resistência", "IP54"]], tags: ["jbl", "bluetooth"], warranty: 12, weight: 60, dims: [8, 8, 4] },
  { slug: "samsung-galaxy-buds3", name: "Samsung Galaxy Buds3 Pro", cat: "fones-de-ouvido", brand: "samsung", store: "technova", kind: "earbuds", options: { Cor: ["Prata", "Branco"] }, colors: pick(["Prata", "Branco"]), price: 129900, about: "Som Hi-Fi de 24 bits, cancelamento adaptativo de ruído e Galaxy AI para tradução.", specs: [["Codec", "SSC Hi-Fi"], ["ANC", "Adaptativo"]], tags: ["galaxy buds"], warranty: 12, weight: 60, dims: [8, 8, 4], stock: "low" },
  // ------------------------------------------------------------ Informática
  { slug: "apple-macbook-air-m3", name: "Apple MacBook Air 13\" M3", cat: "notebooks", brand: "apple", store: "mercatto", kind: "laptop", options: { "Memória": ["16 GB", "24 GB"], Cor: ["Prata", "Grafite"] }, colors: { Prata: "silver", Grafite: "graphite" }, price: 899900, compare: 999900, step: { "24 GB": 150000 }, about: "Leve, silencioso e com até 18 horas de bateria. O chip M3 entrega desempenho para trabalho e criatividade.", specs: [["Processador", "Apple M3 8 núcleos"], ["Armazenamento", "256 GB SSD"], ["Tela", '13,6" Liquid Retina'], ["Bateria", "Até 18 h"]], attrs: { processador: "Apple M3", memoria_ram: "16 GB", tela: '13"' }, tags: ["macbook", "macos"], warranty: 12, included: ["MacBook Air", "Fonte USB-C 30 W", "Cabo"], weight: 1240, dims: [3, 22, 31], freeShipping: true, featured: true },
  { slug: "dell-inspiron-15", name: "Notebook Dell Inspiron 15 Intel Core i5", cat: "notebooks", brand: "dell", store: "mercatto", kind: "laptop", options: { "Memória": ["8 GB", "16 GB"] }, color: "silver", price: 329900, compare: 399900, step: { "16 GB": 40000 }, about: "Tela Full HD de 15,6\", SSD rápido e teclado numérico — produtividade para estudo e trabalho.", specs: [["Processador", "Intel Core i5 13ª geração"], ["Armazenamento", "512 GB SSD"], ["Tela", '15,6" Full HD 120 Hz'], ["Sistema", "Windows 11"]], attrs: { processador: "Intel Core i5", memoria_ram: "8 GB", tela: '15,6"' }, tags: ["notebook", "windows"], warranty: 12, weight: 1900, dims: [4, 25, 36], freeShipping: true },
  { slug: "lenovo-ideapad-slim-3", name: "Notebook Lenovo IdeaPad Slim 3 Ryzen 7", cat: "notebooks", brand: "lenovo", store: "technova", kind: "laptop", color: "gray", price: 349900, compare: 419900, about: "AMD Ryzen 7, 16 GB de RAM e SSD de 512 GB em um corpo fino e leve.", specs: [["Processador", "AMD Ryzen 7 7730U"], ["RAM", "16 GB"], ["Armazenamento", "512 GB SSD"]], attrs: { processador: "AMD Ryzen 7", memoria_ram: "16 GB", tela: '15,6"' }, tags: ["ideapad"], warranty: 12, weight: 1620, dims: [4, 24, 36] },
  { slug: "acer-nitro-v15", name: "Notebook Gamer Acer Nitro V15 RTX 4050", cat: "notebooks", brand: "acer", store: "technova", kind: "laptop", color: "black", price: 549900, compare: 649900, about: "Placa de vídeo GeForce RTX 4050, tela de 144 Hz e refrigeração dupla para jogos pesados.", specs: [["Processador", "Intel Core i5 13420H"], ["Placa de vídeo", "RTX 4050 6 GB"], ["Tela", '15,6" 144 Hz']], attrs: { processador: "Intel Core i5", memoria_ram: "8 GB", tela: '15,6"' }, tags: ["gamer"], warranty: 12, weight: 2100, dims: [4, 26, 37], stock: "low" },
  { slug: "lg-monitor-ultragear-27", name: "Monitor Gamer LG UltraGear 27\" 180 Hz", cat: "monitores", brand: "lg", store: "mercatto", kind: "monitor", color: "black", price: 119900, compare: 149900, about: "Painel IPS de 27\", 180 Hz e 1 ms com HDR10 para jogos fluidos.", specs: [["Tamanho", '27"'], ["Taxa de atualização", "180 Hz"], ["Resolução", "Full HD"]], attrs: { tela: '27"' }, tags: ["monitor gamer"], warranty: 12, weight: 4800, dims: [45, 62, 20], freeShipping: true },
  { slug: "samsung-monitor-24", name: "Monitor Samsung 24\" Full HD", cat: "monitores", brand: "samsung", store: "technova", kind: "monitor", color: "black", price: 69990, about: "Design sem bordas, painel IPS e modo de proteção ocular.", specs: [["Tamanho", '24"'], ["Painel", "IPS 75 Hz"]], attrs: { tela: '24"' }, tags: ["monitor"], warranty: 12, weight: 3200, dims: [40, 55, 18] },
  { slug: "logitech-mx-keys", name: "Teclado sem fio Logitech MX Keys S", cat: "perifericos", brand: "logitech", store: "mercatto", kind: "keyboard", options: { Cor: ["Grafite", "Branco"] }, colors: { Grafite: "graphite", Branco: "white" }, price: 79990, compare: 89990, about: "Teclas esféricas retroiluminadas, conexão com até 3 dispositivos e bateria recarregável.", specs: [["Conexão", "Bluetooth e receptor Logi Bolt"], ["Bateria", "Até 10 dias com iluminação"]], tags: ["teclado"], warranty: 12, weight: 810, dims: [4, 13, 43] },
  { slug: "logitech-mx-master-3s", name: "Mouse Logitech MX Master 3S", cat: "perifericos", brand: "logitech", store: "mercatto", kind: "mouse", options: { Cor: ["Grafite", "Cinza"] }, colors: { Grafite: "graphite", Cinza: "gray" }, price: 59990, compare: 69990, about: "Sensor de 8.000 DPI, cliques silenciosos e rolagem MagSpeed ultrarrápida.", specs: [["DPI", "8.000"], ["Bateria", "Até 70 dias"]], tags: ["mouse"], warranty: 12, weight: 300, dims: [6, 9, 13], featured: true },
  { slug: "mercatto-essentials-mouse", name: "Mouse sem fio Mercatto Essentials", cat: "perifericos", brand: "mercatto-essentials", store: "mercatto", kind: "mouse", options: { Cor: ["Preto", "Branco", "Rosa"] }, colors: pick(["Preto", "Branco", "Rosa"]), price: 4990, compare: 7990, about: "Mouse silencioso, leve e com pilha que dura até 12 meses. Marca própria Mercatto.", specs: [["DPI", "1.600"], ["Conexão", "2,4 GHz"]], tags: ["marca própria"], warranty: 6, weight: 120, dims: [5, 7, 11], freeShipping: true },
  { slug: "apple-ipad-10", name: "Apple iPad (10ª geração) Wi‑Fi 64 GB", cat: "tablets", brand: "apple", store: "mercatto", kind: "tablet", options: { Cor: ["Azul", "Rosa", "Prata"] }, colors: pick(["Azul", "Rosa", "Prata"]), price: 299900, compare: 349900, about: "Tela Liquid Retina de 10,9\", chip A14 Bionic e câmera frontal na horizontal.", specs: [["Tela", '10,9" Liquid Retina'], ["Processador", "A14 Bionic"]], attrs: { tela: '11"' }, tags: ["ipad"], warranty: 12, weight: 480, dims: [3, 18, 25], freeShipping: true },
  { slug: "samsung-galaxy-tab-s9-fe", name: "Samsung Galaxy Tab S9 FE", cat: "tablets", brand: "samsung", store: "technova", kind: "tablet", options: { Cor: ["Grafite", "Prata"] }, colors: { Grafite: "graphite", Prata: "silver" }, price: 249900, about: "S Pen inclusa, resistência à água IP68 e tela de 10,9\" com 90 Hz.", specs: [["Tela", '10,9" 90 Hz'], ["Caneta", "S Pen inclusa"]], attrs: { tela: '11"' }, tags: ["galaxy tab"], warranty: 12, weight: 520, dims: [3, 18, 25] },
  // ------------------------------------------------------------ Games
  { slug: "playstation-5-slim", name: "Console PlayStation 5 Slim", cat: "consoles", brand: "sony", store: "mercatto", kind: "console", options: { "Edição": ["Com leitor de disco", "Digital"] }, color: "white", price: 379900, compare: 449900, step: { Digital: -50000 }, about: "SSD ultrarrápido, áudio 3D Tempest e feedback tátil com o controle DualSense.", specs: [["Armazenamento", "1 TB SSD"], ["Resolução", "Até 4K 120 fps"]], attrs: { plataforma: "PlayStation" }, tags: ["ps5", "sony"], warranty: 12, included: ["Console", "Controle DualSense", "Cabo HDMI"], weight: 3200, dims: [12, 36, 45], freeShipping: true, featured: true },
  { slug: "xbox-series-s", name: "Console Xbox Series S 512 GB", cat: "consoles", brand: "microsoft", store: "technova", kind: "console", color: "white", price: 249900, compare: 299900, about: "O menor Xbox de todos, com jogos em até 1440p e 120 fps e Game Pass.", specs: [["Armazenamento", "512 GB SSD"]], attrs: { plataforma: "Xbox" }, tags: ["xbox"], warranty: 12, weight: 1930, dims: [10, 30, 35] },
  { slug: "nintendo-switch-oled", name: "Console Nintendo Switch OLED", cat: "consoles", brand: "nintendo", store: "mercatto", kind: "console", options: { Cor: ["Branco", "Neon"] }, colors: { Branco: "white", Neon: "red" }, price: 229900, about: "Tela OLED de 7\", base com porta LAN e 64 GB de armazenamento.", specs: [["Tela", '7" OLED'], ["Armazenamento", "64 GB"]], attrs: { plataforma: "Nintendo Switch" }, tags: ["switch"], warranty: 12, weight: 1500, dims: [12, 28, 38], stock: "low" },
  { slug: "controle-dualsense", name: "Controle sem fio DualSense", cat: "controles", brand: "sony", store: "mercatto", kind: "controller", options: { Cor: ["Branco", "Preto", "Azul", "Vermelho"] }, colors: { Branco: "white", Preto: "black", Azul: "blue", Vermelho: "red" }, price: 44990, compare: 54990, about: "Gatilhos adaptáveis, feedback tátil e microfone embutido.", specs: [["Conexão", "Bluetooth / USB-C"]], attrs: { plataforma: "PlayStation" }, tags: ["ps5", "controle"], warranty: 12, weight: 300, dims: [7, 16, 11], freeShipping: true },
  { slug: "controle-xbox-wireless", name: "Controle sem fio Xbox", cat: "controles", brand: "microsoft", store: "technova", kind: "controller", options: { Cor: ["Preto", "Branco", "Azul"] }, colors: pick(["Preto", "Branco", "Azul"]), price: 39990, about: "Pegada texturizada, botão de compartilhamento e compatibilidade com PC e celular.", specs: [["Conexão", "Bluetooth / USB-C"]], attrs: { plataforma: "Xbox" }, tags: ["xbox", "controle"], warranty: 12, weight: 300, dims: [7, 16, 11] },
  { slug: "headset-gamer-hyper", name: "Headset Gamer 7.1 com microfone", cat: "headsets-gamer", brand: "logitech", store: "technova", kind: "headset", options: { Cor: ["Preto", "Branco"] }, colors: pick(["Preto", "Branco"]), price: 39990, compare: 49990, about: "Som surround 7.1, microfone removível com cancelamento de ruído e almofadas de memória.", specs: [["Som", "Surround 7.1"], ["Conexão", "USB e P2"]], attrs: { plataforma: "PC" }, tags: ["headset"], warranty: 12, weight: 400, dims: [10, 20, 22] },
  // ------------------------------------------------------------ TV e Áudio
  { slug: "samsung-smart-tv-55-crystal", name: "Smart TV Samsung 55\" Crystal UHD 4K", cat: "smart-tvs", brand: "samsung", store: "mercatto", kind: "tv", options: { Tamanho: ['50"', '55"', '65"'] }, color: "black", price: 259900, compare: 329900, step: { '50"': -40000, '65"': 120000 }, about: "Processador Crystal 4K, Tizen com apps de streaming e Alexa integrada.", specs: [["Resolução", "4K UHD"], ["Sistema", "Tizen"], ["HDMI", "3 portas"]], attrs: { tamanho_tela: '55"', resolucao: "4K" }, tags: ["smart tv", "4k"], warranty: 12, weight: 15000, dims: [80, 125, 15], freeShipping: true, featured: true },
  { slug: "lg-oled-evo-c4", name: "Smart TV LG OLED evo C4 65\" 4K 144 Hz", cat: "smart-tvs", brand: "lg", store: "technova", kind: "tv", color: "black", price: 899900, compare: 1099900, about: "Pixels autoiluminados, processador α9 Gen7 com IA e 144 Hz para jogos.", specs: [["Painel", "OLED evo"], ["Taxa", "144 Hz"], ["HDMI", "4x HDMI 2.1"]], attrs: { tamanho_tela: '65"', resolucao: "4K" }, tags: ["oled"], warranty: 12, weight: 18000, dims: [90, 145, 15] },
  { slug: "philips-smart-tv-43", name: "Smart TV Philips 43\" Full HD", cat: "smart-tvs", brand: "philips", store: "technova", kind: "tv", color: "black", price: 149900, about: "Full HD, Wi‑Fi integrado e acesso aos principais aplicativos.", specs: [["Resolução", "Full HD"]], attrs: { tamanho_tela: '43"', resolucao: "Full HD" }, tags: ["smart tv"], warranty: 12, weight: 7000, dims: [60, 97, 12] },
  { slug: "jbl-soundbar-300", name: "Soundbar JBL Bar 300 5.0 Dolby Atmos", cat: "soundbars", brand: "jbl", store: "mercatto", kind: "soundbar", color: "black", price: 239900, compare: 289900, about: "Som imersivo Dolby Atmos com MultiBeam, sem precisar de subwoofer.", specs: [["Potência", "260 W"], ["Canais", "5.0"]], tags: ["soundbar"], warranty: 12, weight: 2800, dims: [10, 82, 12], freeShipping: true },
  { slug: "jbl-flip-6", name: "Caixa de som JBL Flip 6", cat: "caixas-de-som", brand: "jbl", store: "mercatto", kind: "speaker", options: { Cor: ["Preto", "Azul", "Vermelho", "Verde"] }, colors: { Preto: "black", Azul: "blue", Vermelho: "red", Verde: "green" }, price: 69990, compare: 89990, about: "Som potente com graves profundos, à prova d'água IP67 e 12 horas de bateria.", specs: [["Potência", "30 W RMS"], ["Bateria", "Até 12 h"], ["Resistência", "IP67"]], tags: ["jbl", "bluetooth"], warranty: 12, weight: 550, dims: [7, 18, 7], freeShipping: true, featured: true },
  { slug: "jbl-go-4", name: "Caixa de som JBL Go 4", cat: "caixas-de-som", brand: "jbl", store: "technova", kind: "speaker", options: { Cor: ["Preto", "Rosa", "Azul"] }, colors: pick(["Preto", "Rosa", "Azul"]), price: 29990, about: "Ultraportátil, à prova d'água e com som JBL Pro.", specs: [["Bateria", "Até 7 h"]], tags: ["jbl"], warranty: 12, weight: 190, dims: [7, 10, 4] },
  { slug: "sony-wh-1000xm5", name: "Headphone Sony WH-1000XM5", cat: "headphones", brand: "sony", store: "mercatto", kind: "headphones", options: { Cor: ["Preto", "Prata"] }, colors: pick(["Preto", "Prata"]), price: 249900, compare: 299900, about: "O melhor cancelamento de ruído da Sony, 30 horas de bateria e chamadas cristalinas.", specs: [["ANC", "Processador V1 + QN1"], ["Bateria", "Até 30 h"]], tags: ["sony", "bluetooth"], warranty: 12, weight: 250, dims: [8, 20, 25], freeShipping: true },
  // ------------------------------------------------------------ Eletrodomésticos
  { slug: "brastemp-geladeira-frost-free-375", name: "Geladeira Brastemp Frost Free Duplex 375 L", cat: "geladeiras", brand: "brastemp", store: "mercatto", kind: "refrigerator", options: { Voltagem: ["110V", "220V"], Cor: ["Inox", "Branco"] }, colors: { Inox: "silver", Branco: "white" }, price: 399900, compare: 479900, about: "Frost Free, compartimento extrafrio e gavetão de hortifrúti com controle de umidade.", specs: [["Capacidade", "375 L"], ["Eficiência", "Selo Procel A"]], attrs: { voltagem: "110V" }, tags: ["geladeira"], warranty: 12, weight: 62000, dims: [175, 62, 70], featured: true },
  { slug: "electrolux-lavadora-12kg", name: "Lavadora Electrolux 12 kg Essential Care", cat: "lavadoras", brand: "electrolux", store: "technova", kind: "washer", options: { Voltagem: ["110V", "220V"] }, color: "white", price: 199900, compare: 249900, about: "Cesto Jet&Clean, função tira-manchas e reaproveitamento de água.", specs: [["Capacidade", "12 kg"]], attrs: { voltagem: "110V" }, tags: ["máquina de lavar"], warranty: 12, weight: 38000, dims: [105, 60, 65] },
  { slug: "electrolux-micro-ondas-31l", name: "Micro-ondas Electrolux 31 L", cat: "micro-ondas", brand: "electrolux", store: "mercatto", kind: "microwave", options: { Voltagem: ["110V", "220V"], Cor: ["Prata", "Branco"] }, colors: { Prata: "silver", Branco: "white" }, price: 79990, compare: 99990, about: "31 litros, função tira-odor e receitas pré-programadas.", specs: [["Capacidade", "31 L"], ["Potência", "900 W"]], attrs: { voltagem: "110V" }, tags: ["micro-ondas"], warranty: 12, weight: 14000, dims: [30, 52, 42], freeShipping: true },
  { slug: "mondial-air-fryer-4l", name: "Fritadeira Air Fryer Mondial 4 L", cat: "air-fryers", brand: "mondial", store: "mercatto", kind: "airfryer", options: { Voltagem: ["110V", "220V"], Cor: ["Preto", "Vermelho"] }, colors: { Preto: "black", Vermelho: "red" }, price: 29990, compare: 44990, about: "Fritura sem óleo, cesto antiaderente de 4 litros e timer de 60 minutos.", specs: [["Capacidade", "4 L"], ["Potência", "1.500 W"]], attrs: { voltagem: "110V" }, tags: ["air fryer"], warranty: 12, weight: 4200, dims: [32, 28, 33], freeShipping: true, featured: true },
  { slug: "philips-airfryer-xl", name: "Airfryer Philips Walita Série 3000 XL", cat: "air-fryers", brand: "philips", store: "casaviva", kind: "airfryer", options: { Voltagem: ["110V", "220V"] }, color: "black", price: 54990, compare: 64990, about: "Tecnologia Rapid Air, 6,2 litros e app com receitas.", specs: [["Capacidade", "6,2 L"]], attrs: { voltagem: "110V" }, tags: ["air fryer"], warranty: 24, weight: 5300, dims: [32, 30, 38] },
  { slug: "arno-liquidificador-power", name: "Liquidificador Arno Power Max 1000 W", cat: "liquidificadores", brand: "arno", store: "casaviva", kind: "blender", options: { Voltagem: ["110V", "220V"] }, color: "black", price: 19990, compare: 24990, about: "1.000 W de potência, jarra de 3,1 litros e 5 velocidades + pulsar.", specs: [["Potência", "1.000 W"], ["Jarra", "3,1 L"]], attrs: { voltagem: "110V" }, tags: ["liquidificador"], warranty: 12, weight: 2800, dims: [42, 22, 22] },
  { slug: "britania-cafeteira-30", name: "Cafeteira Elétrica Britânia 30 xícaras", cat: "cafeteiras", brand: "britania", store: "casaviva", kind: "coffeemaker", options: { Voltagem: ["110V", "220V"], Cor: ["Preto", "Vermelho"] }, colors: { Preto: "black", Vermelho: "red" }, price: 11990, about: "Corta-pingos, placa aquecedora e filtro permanente.", specs: [["Capacidade", "30 xícaras"]], attrs: { voltagem: "110V" }, tags: ["café"], warranty: 12, weight: 1500, dims: [32, 20, 24], stock: "zero" },
  { slug: "robo-aspirador-smart", name: "Robô Aspirador Inteligente com Mapeamento", cat: "aspiradores", brand: "xiaomi", store: "technova", kind: "robot-vacuum", options: { Cor: ["Branco", "Preto"] }, colors: pick(["Branco", "Preto"]), price: 159900, compare: 219900, about: "Mapeamento a laser, aspira e passa pano, controle pelo app e retorno automático à base.", specs: [["Sucção", "4.000 Pa"], ["Bateria", "Até 150 min"]], tags: ["robô aspirador"], warranty: 12, weight: 3800, dims: [10, 35, 35] },
  // ------------------------------------------------------------ Casa
  { slug: "cadeira-escritorio-ergonomica", name: "Cadeira de Escritório Ergonômica com Apoio Lombar", cat: "moveis", brand: "mercatto-essentials", store: "mercatto", kind: "office-chair", options: { Cor: ["Preto", "Cinza"] }, colors: { Preto: "black", Cinza: "gray" }, price: 79990, compare: 119990, about: "Encosto em tela respirável, apoio lombar ajustável e braços 3D. Marca própria Mercatto.", specs: [["Peso suportado", "120 kg"], ["Regulagem", "Altura, inclinação e braços"]], tags: ["home office"], warranty: 12, weight: 15000, dims: [30, 65, 70], featured: true },
  { slug: "sofa-retratil-3-lugares", name: "Sofá Retrátil e Reclinável 3 Lugares", cat: "moveis", store: "casaviva", kind: "sofa", options: { Cor: ["Cinza", "Bege", "Azul"] }, colors: { Cinza: "gray", Bege: "beige", Azul: "navy" }, price: 189900, compare: 249900, about: "Assento retrátil, encosto reclinável e tecido suede de fácil limpeza.", specs: [["Largura", "2,10 m"], ["Tecido", "Suede"]], tags: ["sala"], warranty: 3, weight: 60000, dims: [95, 210, 100] },
  { slug: "luminaria-mesa-led", name: "Luminária de Mesa LED Articulada", cat: "iluminacao", store: "casaviva", kind: "lamp", options: { Cor: ["Preto", "Branco", "Dourado"] }, colors: pick(["Preto", "Branco", "Dourado"]), price: 8990, compare: 12990, about: "3 temperaturas de cor, regulagem de intensidade e braço articulado.", specs: [["Potência", "8 W LED"]], tags: ["luminária"], warranty: 6, weight: 900, dims: [45, 15, 15] },
  { slug: "tramontina-jogo-panelas", name: "Jogo de Panelas Tramontina Antiaderente 5 peças", cat: "cozinha", brand: "tramontina", store: "mercatto", kind: "cookware", options: { Cor: ["Vermelho", "Grafite"] }, colors: { Vermelho: "red", Grafite: "graphite" }, price: 39990, compare: 54990, about: "Revestimento antiaderente Starflon, cabos baquelite e tampas de vidro.", specs: [["Peças", "5"], ["Fogão", "Gás, elétrico e vitrocerâmico"]], tags: ["panelas"], warranty: 12, weight: 5000, dims: [25, 40, 40], freeShipping: true },
  // ------------------------------------------------------------ Moda
  { slug: "camiseta-basica-algodao", name: "Camiseta Básica 100% Algodão", cat: "camisetas", brand: "mercatto-essentials", store: "urbanstep", kind: "tshirt", options: { Tamanho: ["P", "M", "G", "GG"], Cor: ["Branco", "Preto", "Azul-marinho"] }, colors: { Branco: "white", Preto: "black", "Azul-marinho": "navy" }, price: 4990, compare: 6990, about: "Malha penteada fio 30.1, toque macio e caimento regular.", specs: [["Tecido", "100% algodão"]], attrs: { genero: "Unissex" }, tags: ["camiseta"], warranty: 3, weight: 200, dims: [3, 25, 30] },
  { slug: "nike-revolution-7", name: "Tênis Nike Revolution 7", cat: "tenis", brand: "nike", store: "urbanstep", kind: "sneaker", options: { Tamanho: ["38", "39", "40", "41", "42", "43"], Cor: ["Preto", "Branco"] }, colors: pick(["Preto", "Branco"]), price: 39990, compare: 49990, about: "Amortecimento macio para corridas leves e uso no dia a dia.", specs: [["Indicado para", "Corrida e caminhada"]], attrs: { genero: "Masculino" }, tags: ["tênis", "corrida"], warranty: 3, weight: 800, dims: [12, 20, 32], featured: true },
  { slug: "adidas-runfalcon", name: "Tênis Adidas Runfalcon 3.0", cat: "tenis", brand: "adidas", store: "urbanstep", kind: "sneaker", options: { Tamanho: ["35", "36", "37", "38", "39"], Cor: ["Rosa", "Branco"] }, colors: pick(["Rosa", "Branco"]), price: 34990, compare: 39990, about: "Cabedal em mesh respirável e entressola Cloudfoam.", specs: [["Indicado para", "Corrida"]], attrs: { genero: "Feminino" }, tags: ["tênis"], warranty: 3, weight: 700, dims: [12, 20, 30], stock: "mixed" },
  { slug: "olympikus-corre-3", name: "Tênis Olympikus Corre 3", cat: "tenis", brand: "olympikus", store: "urbanstep", kind: "sneaker", options: { Tamanho: ["39", "40", "41", "42"], Cor: ["Azul", "Laranja"] }, colors: { Azul: "blue", Laranja: "orange" }, price: 39990, about: "Tênis de corrida nacional com espuma de alto retorno de energia.", specs: [["Drop", "8 mm"]], attrs: { genero: "Unissex" }, tags: ["corrida"], warranty: 3, weight: 700, dims: [12, 20, 32] },
  { slug: "mochila-notebook-antifurto", name: "Mochila Antifurto para Notebook 15,6\"", cat: "mochilas", brand: "mercatto-essentials", store: "mercatto", kind: "backpack", options: { Cor: ["Preto", "Cinza", "Azul-marinho"] }, colors: { Preto: "black", Cinza: "gray", "Azul-marinho": "navy" }, price: 14990, compare: 19990, about: "Zíper oculto, entrada USB e compartimento acolchoado para notebook.", specs: [["Capacidade", "25 L"], ["Material", "Poliéster impermeável"]], attrs: { genero: "Unissex" }, tags: ["mochila"], warranty: 6, weight: 900, dims: [15, 30, 45], freeShipping: true },
  { slug: "relogio-classico-aco", name: "Relógio Analógico Clássico Aço Inoxidável", cat: "relogios", store: "urbanstep", kind: "wristwatch", options: { Cor: ["Prata", "Dourado", "Preto"] }, colors: pick(["Prata", "Dourado", "Preto"]), price: 25990, compare: 32990, about: "Caixa de 42 mm, vidro mineral e resistência à água 5 ATM.", specs: [["Caixa", "42 mm"], ["Resistência", "5 ATM"]], attrs: { genero: "Masculino" }, tags: ["relógio"], warranty: 12, weight: 300, dims: [8, 10, 10] },
  { slug: "oculos-sol-polarizado", name: "Óculos de Sol Polarizado Aviador", cat: "oculos", store: "urbanstep", kind: "sunglasses", options: { Cor: ["Dourado", "Preto", "Prata"] }, colors: pick(["Dourado", "Preto", "Prata"]), price: 12990, about: "Lentes polarizadas com proteção UV400 e armação metálica leve.", specs: [["Proteção", "UV400"]], attrs: { genero: "Unissex" }, tags: ["óculos"], warranty: 3, weight: 150, dims: [5, 16, 7] },
  // ------------------------------------------------------------ Beleza
  { slug: "natura-essencial-100ml", name: "Perfume Natura Essencial Exclusivo 100 ml", cat: "perfumes", brand: "natura", store: "bellapele", kind: "perfume", color: "gold", price: 23990, compare: 26990, about: "Fragrância amadeirada intensa com notas de cumaru e cedro.", specs: [["Volume", "100 ml"], ["Família", "Amadeirado"]], tags: ["perfume"], weight: 400, dims: [16, 9, 6], featured: true },
  { slug: "boticario-floratta-75ml", name: "Perfume O Boticário Floratta Blue 75 ml", cat: "perfumes", brand: "boticario", store: "bellapele", kind: "perfume", color: "blue", price: 12990, about: "Floral frutal com notas de flor de lótus e frutas vermelhas.", specs: [["Volume", "75 ml"]], tags: ["perfume"], weight: 300, dims: [14, 8, 5] },
  { slug: "serum-vitamina-c", name: "Sérum Facial Vitamina C 10% 30 ml", cat: "skincare", store: "bellapele", kind: "skincare", color: "orange", price: 6990, compare: 8990, about: "Antioxidante, uniformiza o tom da pele e ilumina. Para todos os tipos de pele.", specs: [["Volume", "30 ml"], ["Ativo", "Vitamina C 10%"]], tags: ["skincare"], weight: 120, dims: [10, 4, 4], freeShipping: true },
  { slug: "hidratante-facial-acido-hialuronico", name: "Hidratante Facial Ácido Hialurônico 50 g", cat: "skincare", store: "bellapele", kind: "skincare", color: "white", price: 5990, about: "Hidratação por 48 h com textura leve em gel-creme.", specs: [["Peso", "50 g"]], tags: ["skincare"], weight: 100, dims: [8, 6, 6] },
  { slug: "secador-profissional-2100w", name: "Secador de Cabelo Profissional 2100 W", cat: "cabelos", brand: "philips", store: "bellapele", kind: "hairdryer", options: { Voltagem: ["110V", "220V"], Cor: ["Preto", "Rosa"] }, colors: { Preto: "black", Rosa: "pink" }, price: 18990, compare: 24990, about: "Tecnologia íons, 3 temperaturas e jato de ar frio.", specs: [["Potência", "2.100 W"]], tags: ["secador"], warranty: 12, weight: 800, dims: [10, 25, 28] },
  // ------------------------------------------------------------ Automotivo
  { slug: "pneu-pirelli-aro-15", name: "Pneu Pirelli Cinturato P1 195/55 R15", cat: "pneus", brand: "pirelli", store: "garagempro", kind: "tire", color: "black", price: 54990, compare: 64990, about: "Pneu de passeio com ótima frenagem no molhado e baixa resistência ao rolamento.", specs: [["Medida", "195/55 R15"], ["Índice de carga", "85"]], attrs: { aro: "15" }, tags: ["pneu"], warranty: 60, weight: 8500, dims: [20, 60, 60] },
  { slug: "pneu-pirelli-aro-17", name: "Pneu Pirelli Scorpion 225/65 R17", cat: "pneus", brand: "pirelli", store: "garagempro", kind: "tire", color: "black", price: 89990, about: "Para SUVs: conforto, durabilidade e segurança em asfalto.", specs: [["Medida", "225/65 R17"]], attrs: { aro: "17" }, tags: ["pneu", "suv"], warranty: 60, weight: 12000, dims: [24, 72, 72], stock: "low" },
  { slug: "camera-veicular-full-hd", name: "Câmera Veicular Dashcam Full HD com Wi‑Fi", cat: "acessorios-automotivos", store: "garagempro", kind: "dashcam", color: "black", price: 24990, compare: 32990, about: "Gravação em loop, visão noturna, sensor G e app para baixar os vídeos.", specs: [["Resolução", "Full HD 1080p"], ["Ângulo", "150°"]], tags: ["dashcam"], warranty: 12, weight: 200, dims: [6, 10, 6] },
  // ------------------------------------------------------------ Ferramentas
  { slug: "bosch-furadeira-impacto", name: "Furadeira de Impacto Bosch GSB 550 W", cat: "ferramentas-eletricas", brand: "bosch", store: "garagempro", kind: "drill", options: { Voltagem: ["110V", "220V"] }, color: "blue", price: 34990, compare: 42990, about: "Leve e compacta, ideal para furar madeira, metal e alvenaria.", specs: [["Potência", "550 W"], ["Mandril", "13 mm"]], attrs: { voltagem: "110V" }, tags: ["furadeira"], warranty: 12, weight: 2000, dims: [10, 25, 30], featured: true },
  { slug: "makita-parafusadeira-12v", name: "Parafusadeira a Bateria Makita 12 V", cat: "ferramentas-eletricas", brand: "makita", store: "garagempro", kind: "drill", color: "green", price: 69990, about: "Duas baterias, carregador rápido e maleta.", specs: [["Tensão", "12 V"], ["Torque", "30 Nm"]], attrs: { voltagem: "Bivolt" }, tags: ["parafusadeira"], warranty: 12, weight: 2500, dims: [12, 30, 35] },
  { slug: "caixa-ferramentas-110-pecas", name: "Kit Ferramentas com Maleta 110 peças", cat: "organizacao", brand: "tramontina", store: "garagempro", kind: "toolbox", options: { Cor: ["Vermelho", "Azul"] }, colors: { Vermelho: "red", Azul: "blue" }, price: 29990, compare: 39990, about: "Chaves, soquetes, alicates e bits em maleta resistente.", specs: [["Peças", "110"]], tags: ["kit ferramentas"], warranty: 12, weight: 5500, dims: [10, 35, 45] },
  // ------------------------------------------------------------ Esportes
  { slug: "caloi-bicicleta-aro-29", name: "Bicicleta Caloi Aro 29 21 Marchas Freio a Disco", cat: "bicicletas", brand: "caloi", store: "garagempro", kind: "bicycle", options: { Tamanho: ["15", "17", "19"], Cor: ["Preto", "Vermelho"] }, colors: { Preto: "black", Vermelho: "red" }, price: 129990, compare: 159990, about: "Quadro de alumínio, suspensão dianteira e freios a disco mecânicos.", specs: [["Aro", "29"], ["Marchas", "21"]], tags: ["bike", "mtb"], warranty: 12, weight: 16000, dims: [25, 80, 145], featured: true },
  { slug: "halter-ajustavel-20kg", name: "Kit Halteres Ajustáveis 20 kg", cat: "musculacao", store: "garagempro", kind: "dumbbell", color: "black", price: 22990, compare: 29990, about: "Anilhas emborrachadas e barras com rosca para treinar em casa.", specs: [["Peso total", "20 kg"]], tags: ["musculação"], warranty: 3, weight: 21000, dims: [20, 40, 40] },
  { slug: "tapete-yoga-tpe", name: "Tapete de Yoga TPE 6 mm Antiderrapante", cat: "yoga", store: "urbanstep", kind: "yoga-mat", options: { Cor: ["Roxo", "Verde", "Azul"] }, colors: { Roxo: "purple", Verde: "green", Azul: "blue" }, price: 12990, compare: 15990, about: "Material ecológico, dupla face antiderrapante e alça de transporte.", specs: [["Espessura", "6 mm"]], tags: ["yoga"], warranty: 3, weight: 900, dims: [15, 15, 62], freeShipping: true },
  { slug: "bola-futebol-campo", name: "Bola de Futebol de Campo Oficial", cat: "futebol", brand: "adidas", store: "urbanstep", kind: "football", color: "white", price: 14990, about: "Costura termossoldada e câmara de butil para melhor retenção de ar.", specs: [["Tamanho", "5"]], tags: ["futebol"], warranty: 3, weight: 450, dims: [23, 23, 23] },
  // ------------------------------------------------------------ Estados especiais
  { slug: "smartphone-rascunho-teste", name: "Smartphone em cadastro (rascunho)", cat: "smartphones", store: "technova", kind: "smartphone", color: "gray", price: 99900, about: "Produto em rascunho — não aparece na loja.", specs: [["Status", "Rascunho"]], weight: 200, dims: [15, 7, 1], status: "DRAFT" },
  { slug: "caixa-som-pausada", name: "Caixa de Som Bluetooth (anúncio pausado)", cat: "caixas-de-som", store: "technova", kind: "speaker", color: "gray", price: 19990, about: "Anúncio pausado pelo vendedor.", specs: [["Status", "Pausado"]], weight: 400, dims: [10, 10, 10], status: "PAUSED" },
];
